"""users_phone_and_email_auth

Revision ID: ce9cb28b9b57
Revises: fb4e3a1f0895
Create Date: 2026-03-04 15:59:29.468568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce9cb28b9b57'
down_revision: Union[str, Sequence[str], None] = 'fb4e3a1f0895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
